# you may add some individual acls
CREATE USER 'PMA_AUTH_USERNAME'@PMA_AUTH_HOSTNAME IDENTIFIED BY 'PMA_AUTH_PASSWORD';
GRANT SELECT, INSERT, DELETE, UPDATE, ALTER ON `phpmyadmin`.* TO 'PMA_AUTH_USERNAME'@PMA_AUTH_HOSTNAME;
